### PR TITLE
Additional styling

### PR DESCRIPTION
**Pull request by taoantaoan**
Implementation of styling and ux principles to better accomodate a variety of learning expenses.

### CODE REVIEW

**Review by annieshinn — APPROVED** [review]
I appreciate the changes to styling in the "Add Card" and "Deck View" pages.

The centering in both and responsive sizing in deck view, to me, seem like intuitive changes.

Great work.

**Review by Rahmteen — COMMENTED** [review]
Great job implementing CSS/Bootstrap, the website definitely has  improved UX and UI functionality.

**Review by astaiglesia — APPROVED** [review]
Lovely styling edits. Good to go

**Review by zbrucker — APPROVED** [review]
CSS revisions enact desired styling. Approved for merge.

**Pull request merged**
