### PR TITLE
Boiler plate

### PR DESCRIPTION
**Pull request by taoantaoan**
Hi team, 

Here is a compilation of the requested changes, more specifically those in our package.json, webpack.config.js, and the tests that we created in our sample React Component(s). Furthermore, the server.js file is now requisitioned to accept basic get requests and handle errors. 

Please let me know if there are changes or technical modifications that you'd like done before we can merge the boiler plate into the main branch. 

Looking forward to criticism and feedback.

Cheers, 

Tolan

### CODE REVIEW

**Review by annieshinn — APPROVED** [review]
Awesome boilerplate.

**Review by Rahmteen — APPROVED** [review]
Thank you for the detailed feedback on changes, we are looking good to move on to the next steps!

**Review by zbrucker — COMMENTED** [review]
I've verified the modifications work on my local machine. Approved for merge.

**Comment by astaiglesia** [comment]
Everything appears as discussed and I have no objections to merging the associated files.

Best,
Alfred

**Comment by Rahmteen** [comment]
Merging updated boilerplate into staging

**Pull request merged**
