### PR TITLE
Read deck functionality

### PR DESCRIPTION
**Pull request by taoantaoan**
As per the requirement spec for the deck functionality, we look-forward to your input in the upcoming code review.

**Features Addressed:**
1. Back-end modularity
2. CRUD - READ operation for a deck of flashcards
3. Adjustment of mongoose model property
4. Update to most recent version of main
5. Reduce learning curve of those involved with future-onboarding

**Solution:**
1. Create separate concerns for deck router and controller
2. Collaborate with front-end team to understand and provide appropriate end-points and request/response objects
3. Update card mongoose  model so that deckId accepts a string 
4. Resolved merge conflicts from front-end’s most recent commit
5. Wrote descriptive comments for any special functionality within files

**Testing:**
 Functionality of get requests has been verified in Postman; branch then by 4+ of organizational team members

### CODE REVIEW

**Comment by taoantaoan** [comment]
As per the requirement spec for the deck functionality, we look-forward to your input in the upcoming code review.

**Features Addressed:**
1. Back-end modularity
2. CRUD - READ operation for a deck of flashcards
3. Adjustment of mongoose model property
4. Update to most recent version of main
5. Reduce learning curve of those involved with future-onboarding

**Solution:**
1. Create separate concerns for deck router and controller
2. Collaborate with front-end team to understand and provide appropriate end-points and request/response objects
3. Update card mongoose  model so that deckId accepts a string 
4. Resolved merge conflicts from front-end’s most recent commit
5. Wrote descriptive comments for any special functionality within files

**Testing:**
 Functionality of get requests has been verified in Postman; branch then by 4+ of organizational team members

**Comment by astaiglesia** [comment]
Features have been addressed as noted in the pull request.
- GET requests procured via Postman produce the intended response objects when routed to the appropriate end points as discussed 
- Code has been commented descriptively for legacy purposes

No exceptions are taken at this time and recommend authorization of pull request.

**Review by zbrucker — APPROVED** [review]
Created a temporary testing branch and tested associated code on my local machine. 

- Front end components render as expected.
- GET requests with param: 'deckId' return all of the cards that are stored in the Mongo database with a deck property of 'deckId'.
- POST requests create a new card document in the Mongo database. 

Approved for merge into staging.

**Comment by annieshinn** [comment]
The features listed seem to have been addressed:

> 1. New files re: Deck have been added and organized
> 2. A Postman test of the READ operation shows a successful response
> 3. The updated model operates as expected
> 4. The code is working off of the most recent update with no errors
> 5. Comments sprinkled into the code are concise yet provide a large amount of context for onboarding new teammates.

After code review and testing -- I approve this pull request. Keep up the good work team.

**Review by astaiglesia — APPROVED** [review]
Features have been addressed as noted in the pull request.
- GET requests procured via Postman produce the intended response objects when routed to the appropriate end points as discussed 
- Code has been commented descriptively for legacy purposes

No exceptions are taken at this time and recommend authorization of pull request.

**Review by annieshinn — APPROVED** [review]
The features listed seem to have been addressed:

> 1. New files re: Deck have been added and organized
> 2. A Postman test of the READ operation shows a successful response
> 3. The updated model operates as expected
> 4. The code is working off of the most recent update with no errors
> 5. Comments sprinkled into the code are concise yet provide a large amount of context for onboarding new teammates.

After code review and testing -- I approve this pull request. Keep up the good work team.

**Pull request merged**
